INSERT INTO breed (species, name, name_kor, code, sex, avg_weight_low, avg_weight_high)
VALUES ('DOG', 'BEA', '비글', 0, 'MALE', 22, 24),
       ('DOG', 'BEA', '비글', 0, 'FEMALE', 20, 22),
       ('DOG', 'BIC', '비숑 프리제', 1, 'MALE', 12, 18),
       ('DOG', 'BIC', '비숑 프리제', 1, 'FEMALE', 12, 18),
       ('DOG', 'BUL', '불독', 2, 'MALE', 50, 55),
       ('DOG', 'BUL', '불독', 2, 'FEMALE', 40, 44),
       ('DOG', 'CHL', '치와와 장모', 3, 'MALE', 6, 8),
       ('DOG', 'CHL', '치와와 장모', 3, 'FEMALE', 5, 7),
       ('DOG', 'CHS', '치와와 단모', 4, 'MALE', 6, 8),
       ('DOG', 'CHS', '치와와 단모', 4, 'FEMALE', 5, 7),
       ('DOG', 'COC', '코커 스패니엘', 5, 'MALE', 28, 34),
       ('DOG', 'COC', '코커 스패니엘', 5, 'FEMALE', 26, 32),
       ('DOG', 'DAL', '닥스훈트 장모', 6, 'MALE', 16, 32),
       ('DOG', 'DAL', '닥스훈트 장모', 6, 'FEMALE', 16, 32),
       ('DOG', 'DAS', '닥스훈트 장모', 7, 'MALE', 16, 32),
       ('DOG', 'DAS', '닥스훈트 단모', 7, 'FEMALE', 16, 32),
       ('DOG', 'DOB', '도베르만 핀셔', 8, 'MALE', 75, 100),
       ('DOG', 'DOB', '도베르만 핀셔', 8, 'FEMALE', 60, 90),
       ('DOG', 'DRI', '시추', 9, 'MALE', 9, 16),
       ('DOG', 'DRI', '시추', 9, 'FEMALE', 9, 16),
       ('DOG', 'GER', '저먼 셰퍼드', 11, 'MALE', 65, 90),
       ('DOG', 'GER', '저먼 셰퍼드', 11, 'FEMALE', 50, 70),
       ('DOG', 'GOL', '골든 리트리버', 12, 'MALE', 65, 75),
       ('DOG', 'GOL', '골든 리트리버', 12, 'FEMALE', 55, 65),
       ('DOG', 'GRE', '그레이트 피레니즈', 13, 'MALE', 100, 110),
       ('DOG', 'GRE', '그레이트 피레니즈', 13, 'FEMALE', 85, 100),
       ('DOG', 'HOU', '하운드', 14, 'MALE', 65, 70),
       ('DOG', 'HOU', '하운드', 14, 'FEMALE', 60, 65),
       ('DOG', 'HUS', '허스키', 15, 'MALE', 45, 60),
       ('DOG', 'HUS', '허스키', 15, 'FEMALE', 35, 50),
       ('DOG', 'JIN', '진돗개', 16, 'MALE', 44, 55),
       ('DOG', 'JIN', '진돗개', 16, 'FEMALE', 33, 44),
       ('DOG', 'LAB', '래브라도 리트리버', 17, 'MALE', 65, 80),
       ('DOG', 'LAB', '래브라도 리트리버', 17, 'FEMALE', 55, 70),
       ('DOG', 'MAL', '말티즈', 18, 'MALE', 6, 9),
       ('DOG', 'MAL', '말티즈', 18, 'FEMALE', 6, 9),
       ('DOG', 'MIL', '믹스 장모', 19, 'MALE', 0, 0),
       ('DOG', 'MIL', '믹스 장모', 19, 'FEMALE', 0, 0),
       ('DOG', 'MIS', '믹스 단모', 20, 'MALE', 1, 6),
       ('DOG', 'MIS', '믹스 단모', 20, 'FEMALE', 1, 6),
       ('DOG', 'MUT', '말라뮤트', 21, 'MALE', 79, 95),
       ('DOG', 'MUT', '말라뮤트', 21, 'FEMALE', 71, 84),
       ('DOG', 'POM', '포메라니안', 22, 'MALE', 3, 7),
       ('DOG', 'POM', '포메라니안', 22, 'FEMALE', 3, 7),
       ('DOG', 'POO', '미니어처 푸들', 23, 'MALE', 10, 15),
       ('DOG', 'POO', '미니어처 푸들', 23, 'FEMALE', 10, 15),
       ('DOG', 'SCH', '슈나우저', 24, 'MALE', 35, 50),
       ('DOG', 'SCH', '슈나우저', 24, 'FEMALE', 30, 45),
       ('DOG', 'SHE', '쉽독', 25, 'MALE', 0, 0),
       ('DOG', 'SHE', '쉽독', 25, 'FEMALE', 0, 0),
       ('DOG', 'TER', '테리어', 26, 'MALE', 0, 0),
       ('DOG', 'TER', '테리어', 26, 'FEMALE', 0, 0),
       ('DOG', 'WEL', '웰시 코기', 27, 'MALE', 26, 30),
       ('DOG', 'WEL', '웰시 코기', 27, 'FEMALE', 22, 26),
       ('CAT', 'ETC', '기타', 28, 'MALE', 0, 0),
       ('CAT', 'ETC', '기타', 28, 'FEMALE', 0, 0),
       ('CAT', 'KOR', '코리안 숏헤어', 29, 'MALE', 8, 12),
       ('CAT', 'KOR', '코리안 숏헤어', 29, 'FEMALE', 8, 12),
       ('CAT', 'PER', '페르시안', 30, 'MALE', 7, 12),
       ('CAT', 'PER', '페르시안', 30, 'FEMALE', 7, 12),
       ('CAT', 'RUS', '러시안 블루', 31, 'MALE', 6, 9),
       ('CAT', 'RUS', '러시안 블루', 31, 'FEMALE', 6, 9),
       ('CAT', 'SCO', '스코티시 폴드', 32, 'MALE', 9, 13),
       ('CAT', 'SCO', '스코티시 폴드', 32, 'FEMALE', 9, 13),
       ('CAT', 'SIA', '샴', 33, 'MALE', 7, 10),
       ('CAT', 'SIA', '샴', 33, 'FEMALE', 7, 10),
       ('CAT', 'TUR', '터키시 앙고라', 34, 'MALE', 8, 11),
       ('CAT', 'TUR', '터키시 앙고라', 34, 'FEMALE', 8, 11);
