INSERT INTO breed (species, name, name_kor, code, sex, avg_weight_low, avg_weight_high)
VALUES ('CAT', 'ETC', '기타(고양이)', 0, 'MALE', 7, 13),
       ('CAT', 'ETC', '기타(고양이)', 0, 'FEMALE', 7, 13),
       ('CAT', 'KOR', '코리안 숏헤어', 1, 'MALE', 8, 12),
       ('CAT', 'KOR', '코리안 숏헤어', 1, 'FEMALE', 8, 12),
       ('DOG', 'BIC', '비숑 프리제', 2, 'MALE', 12, 18),
       ('DOG', 'BIC', '비숑 프리제', 2, 'FEMALE', 12, 18),
       ('DOG', 'CHI', '치와와', 3, 'MALE', 6, 8),
       ('DOG', 'CHI', '치와와', 3, 'FEMALE', 5, 7),
       ('DOG', 'ETC', '기타(강아지)', 4, 'MALE', 0, 0),
       ('DOG', 'ETC', '기타(강아지)', 4, 'FEMALE', 0, 0),
       ('DOG', 'MAL', '말티즈', 5, 'MALE', 6, 9),
       ('DOG', 'MAL', '말티즈', 5, 'FEMALE', 6, 9),
       ('DOG', 'POM', '포메라니안', 6, 'MALE', 3, 7),
       ('DOG', 'POM', '포메라니안', 6, 'FEMALE', 3, 7),
       ('DOG', 'POO', '미니어처 푸들', 7, 'MALE', 10, 15),
       ('DOG', 'POO', '미니어처 푸들', 7, 'FEMALE', 10, 15),
       ('DOG', 'TER', '테리어', 8, 'MALE', 0, 0),
       ('DOG', 'TER', '테리어', 8, 'FEMALE', 0, 0);
