name: "[dev] Deploy"

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "gradle"

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon --x test

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            DB_URL=${{ secrets.DEV_DB_URL }}
            DB_USERNAME=${{ secrets.DEV_DB_USERNAME }} 
            DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_ISSUER }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            AI_SERVER_URL=${{ secrets.AI_SERVER_URL }}
            OPENAI_KEY=${{ secrets.OPENAI_KEY }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fatpet-server-dev:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: SSH into EC2 Instance and Run Docker Container
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          key: ${{ secrets.DEV_EC2_PRIVATE_KEY }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          port: ${{ secrets.DEV_EC2_PORT }}
          script: |
            sudo docker rm -f $(sudo docker ps -aq)
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fatpet-server-dev:latest
            sudo docker stop $(sudo docker ps -aq)
            sudo docker run -d -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/fatpet-server-dev:latest
